{% set name = "pywwt" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af9a609692e2d4422db3c80ab50fc2fbbf1b7821e32b1a76535a9727de82b475

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - nodejs =17  # prevent unnecessary matrixing here

  host:
    - python >=3.7
    - setuptools
    - pip

  run:
    # Keep alphabetized!
    - astropy >=1.0
    - beautifulsoup4
    - ipyevents
    - ipywidgets >=7.0
    - jupyterlab
    - lxml
    - matplotlib-base >=3
    - notebook
    - numpy >=1.9
    - pyqt
    - python >=3.7
    - python-dateutil
    - pytz
    - qtpy
    - reproject >=0.8
    - requests
    - toasty >=0.15
    - tornado
    - traitlets
    - widgetsnbextension
    - wwt_data_formats >=0.12
    - wwt_kernel_data_relay >=0.2

test:
  imports:
    - pywwt
  requires:
    - nbclassic
    - xorg-libx11  # needed for Tk import on Azure CI

about:
  home: http://github.com/WorldWideTelescope/pywwt
  summary: WorldWide Telescope in Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - pkgw
