{% set name = "pywwt" %}
{% set version = "0.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2a4a82d141be383111a1b746481228ba625cb1b5418e8a2f752e8b524766c86

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - nodejs =17  # prevent unnecessary matrixing here

  host:
    - python {{ python_min }}
    - setuptools
    - pip

  run:
    # Keep alphabetized!
    - astropy-base >=1.0
    - beautifulsoup4
    - ipyevents
    - ipywidgets >=7.0
    - jupyterlab
    - lxml
    - matplotlib-base >=3
    - notebook
    - numpy >=1.9
    - pyqt
    - python >={{ python_min }}
    - python-dateutil
    - pytz
    - qtpy
    - reproject >=0.8
    - requests
    - toasty >=0.20
    - tornado
    - traitlets
    - widgetsnbextension
    - wwt_data_formats >=0.12
    - wwt_kernel_data_relay >=0.2

test:
  imports:
    - pywwt
  requires:
    - nbclassic
    - python {{ python_min }}
    - xorg-libx11  # needed for Tk import on Azure CI

about:
  home: http://github.com/WorldWideTelescope/pywwt
  summary: WorldWide Telescope in Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - pkgw
